# Generated by Django 5.0.6 on 2024-11-10 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(choices=[('Snippet', 'SNIPPETS'), ('User', 'USERS')], max_length=100)),
                ('model_id', models.IntegerField()),
                ('action', models.CharField(choices=[('E', 'D'), ('P', 'U'), ('R', 'C')], max_length=10)),
                ('action_taken_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
